-- Dados importados do projeto anterior. Confira preços e disponibilidade antes de publicar.
insert into public.products (id,name,category,price,unit,description,image,sizes,colors,availability,visible) values
(1, 'Pijama Americano', 'pijama', 55, 'conjunto', 'Conjunto calça e camiseta quentinho e estampado, ideal para noites confortáveis e femininas.', '/catalog/product-1.png', ARRAY['P','M','G','GG']::text[], ARRAY['Rosa','Azul','Lilás']::text[], 'encomenda', true),
(2, 'Camisola de Renda', 'lingerie', 60, 'peça', 'Camisola elegante com detalhes em renda delicada, perfeita para noites especiais e presentes.', '/catalog/product-2.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Rosa','Branco','Preto','Vinho']::text[], 'encomenda', true),
(3, 'Baby Doll', 'lingerie', 55, 'conjunto', 'Conjunto baby doll curto e delicado, confortável e feminino para dias quentes.', '/catalog/product-3.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Rosa','Preto','Branco']::text[], 'encomenda', true),
(4, 'Baby Doll Suede', 'lingerie', 50, 'conjunto', 'Baby doll em tecido suede macio e sofisticado, leve e com toque aveludado.', '/catalog/product-4.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Rosa','Nude','Vinho','Preto']::text[], 'encomenda', true),
(5, 'Conjunto Infantil Americano', 'pijama', 50, 'conjunto', 'Conjunto pijama infantil estampado, macio e confortável para as crianças.', '/catalog/product-5.webp', ARRAY['2','4','6','8','10','12']::text[], ARRAY['Rosa','Azul','Verde']::text[], 'encomenda', true),
(6, 'Macaquito Suede', 'lingerie', 40, 'peça', 'Macaquito feminino em suede aveludado, estiloso e confortável para o dia a dia.', '/catalog/product-6.jpg', ARRAY['P','M','G','GG']::text[], ARRAY['Nude','Rosa','Preto','Bordô']::text[], 'encomenda', true),
(7, 'Lingerie Renda Bordada', 'lingerie', 60, 'conjunto', 'Conjunto lingerie com renda bordada de alta qualidade, sofisticado e delicado.', '/catalog/product-7.jpg', ARRAY['P','M','G','GG']::text[], ARRAY['Preto','Vinho','Rosa','Nude']::text[], 'encomenda', true),
(8, 'Lingerie de Renda', 'lingerie', 50, 'conjunto', 'Conjunto lingerie em renda delicada, confortável e feminina para o dia a dia.', '/catalog/product-8.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Preto','Rosa','Branco','Vermelho']::text[], 'encomenda', true),
(9, 'Calcinha Semi Fio', 'calcinha', 5, 'unidade', 'Calcinha semi fio em renda delicada. Vendida por unidade — compre quantas quiser!', '/catalog/product-9.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Preto','Rosa','Branco','Vinho','Bege']::text[], 'disponivel', true),
(10, 'Calcinha Normal', 'calcinha', 6, 'unidade', 'Calcinha básica confortável em renda. Vendida por unidade.', '/catalog/product-10.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Preto','Rosa','Branco','Bege','Azul']::text[], 'disponivel', true),
(11, 'Sabonete Artesanal', 'sabonete', 10, 'unidade', 'Sabonete decorativo artesanal de alta qualidade. Perfeito para usar ou presentear. Formatos variados.', '/catalog/product-11.jpg', ARRAY[]::text[], ARRAY['Rosa','Branco','Lilás','Pêssego']::text[], 'encomenda', true),
(12, 'Sabonete Caseiro Artesanal', 'sabonete', 10, 'unidade', 'Sabonete caseiro artesanal disponível em qualquer fragrância. Produção sob encomenda com materiais selecionados.', '/catalog/product-12.jpg', ARRAY[]::text[], ARRAY['Qualquer fragrância']::text[], 'encomenda', true)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.products', 'id'), greatest(coalesce((select max(id) from public.products), 1), 1));
