-- ============================================
-- Encanto Feminino - configuracao unica do Supabase
-- Rode no SQL Editor do projeto.
-- ============================================


create table public.catalog_admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.catalog_admins enable row level security;
revoke all on public.catalog_admins from anon, authenticated;
grant select on public.catalog_admins to authenticated;
create policy "Admin can check own access" on public.catalog_admins
  for select to authenticated using (user_id = (select auth.uid()));

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 120),
  category text not null check (category in ('pijama', 'lingerie', 'calcinha', 'sabonete')),
  price numeric(10,2) not null check (price >= 0),
  unit text not null check (length(trim(unit)) > 0),
  description text not null default '',
  image text not null check (image ~ '^(https://|/catalog/)'),
  sizes text[] not null default '{}',
  colors text[] not null default '{}',
  availability text not null default 'encomenda' check (availability in ('disponivel', 'encomenda', 'indisponivel')),
  visible boolean not null default true
);
alter table public.products enable row level security;
revoke all on public.products from anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert, update on public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;
create policy "Visitors see visible products" on public.products
  for select to anon, authenticated using (visible = true);
create policy "Admins see full catalog" on public.products
  for select to authenticated using (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));
create policy "Admins create products" on public.products
  for insert to authenticated with check (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));
create policy "Admins edit products" on public.products
  for update to authenticated
  using (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())))
  with check (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-photos', 'product-photos', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']);
create policy "Admins upload product photos" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'product-photos' and exists (select 1 from public.catalog_admins where user_id = (select auth.uid()))
  );


-- Apply after 202609200001_catalog.sql. Existing products keep their current status.
create or replace function public.valid_product_variants(items jsonb)
returns boolean language plpgsql immutable set search_path = '' as $$
declare
  item jsonb;
  seen_ids text[] := '{}';
  seen_pairs text[] := '{}';
  pair text;
begin
  if jsonb_typeof(items) is distinct from 'array' then return false; end if;
  if jsonb_array_length(items) > 100 then return false; end if;
  for item in select value from jsonb_array_elements(items) loop
    if jsonb_typeof(item) is distinct from 'object'
      or jsonb_typeof(item->'id') is distinct from 'string'
      or jsonb_typeof(item->'size') is distinct from 'string'
      or jsonb_typeof(item->'color') is distinct from 'string'
      or jsonb_typeof(item->'availability') is distinct from 'string'
      then return false; end if;
    if length(btrim(item->>'id')) = 0
      or length(item->>'id') > 100
      or length(item->>'size') > 40
      or length(item->>'color') > 60
      or (length(btrim(item->>'size')) = 0 and length(btrim(item->>'color')) = 0)
      or (item->>'availability') not in ('disponivel','encomenda','indisponivel')
      then return false; end if;
    pair := jsonb_build_array(lower(btrim(item->>'size')), lower(btrim(item->>'color')))::text;
    if (item->>'id') = any(seen_ids) or pair = any(seen_pairs) then return false; end if;
    seen_ids := array_append(seen_ids, item->>'id');
    seen_pairs := array_append(seen_pairs, pair);
  end loop;
  return true;
end;
$$;

create or replace function public.valid_product_images(items text[])
returns boolean language sql immutable set search_path = '' as $$
  select cardinality(items) <= 7 and not exists (
    select 1 from unnest(items) as image
    where image is null or image !~ '^(https://|/catalog/)'
  );
$$;

alter table public.products
  add column images text[] not null default '{}' check (public.valid_product_images(images)),
  add column variants jsonb not null default '[]' check (public.valid_product_variants(variants)),
  add column lead_time text not null default '' check (length(lead_time) <= 160);

-- Ensure every client sees the same aggregate status, including edits outside the panel.
create or replace function public.sync_product_options()
returns trigger language plpgsql set search_path = '' as $$
begin
  if not public.valid_product_variants(new.variants) then
    raise exception 'Invalid product variants' using errcode = '23514';
  end if;
  if jsonb_array_length(new.variants) > 0 then
    new.availability := case
      when exists (select 1 from jsonb_array_elements(new.variants) v where v->>'availability' = 'disponivel') then 'disponivel'
      when exists (select 1 from jsonb_array_elements(new.variants) v where v->>'availability' = 'encomenda') then 'encomenda'
      else 'indisponivel' end;
    select coalesce(array_agg(distinct btrim(v->>'size')) filter (where btrim(v->>'size') <> ''), '{}'::text[])
      into new.sizes from jsonb_array_elements(new.variants) v;
    select coalesce(array_agg(distinct btrim(v->>'color')) filter (where btrim(v->>'color') <> ''), '{}'::text[])
      into new.colors from jsonb_array_elements(new.variants) v;
  end if;
  return new;
end;
$$;

create trigger products_sync_options before insert or update on public.products
for each row execute function public.sync_product_options();


-- ConfiguraÃ§Ãµes da marca editÃ¡veis pela dona no painel (/admin). Linha Ãºnica.
create table public.brand_settings (
  id int primary key default 1 check (id = 1),
  name text not null check (length(trim(name)) between 1 and 60),
  whatsapp text not null default '' check (whatsapp ~ '^\+?[0-9]{10,15}$'),
  instagram text not null default '' check (instagram ~ '^[A-Za-z0-9._]{1,30}$'),
  logo text not null default '' check (logo ~ '^(https://|/catalog/)'),
  updated_at timestamptz not null default now()
);

insert into public.brand_settings (id, name, whatsapp, instagram, logo)
values (1, 'Encanto Feminino', '5511999999999', 'encantofeminino.demo', '/catalog/logo.svg');

alter table public.brand_settings enable row level security;
revoke all on public.brand_settings from anon, authenticated;
grant select on public.brand_settings to anon, authenticated;
grant insert, update on public.brand_settings to authenticated;

create policy "Visitors read brand settings" on public.brand_settings
  for select to anon, authenticated using (true);

create policy "Admins manage brand settings" on public.brand_settings
  for all to authenticated
  using (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())))
  with check (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));

-- Dados importados do projeto anterior. Confira preÃ§os e disponibilidade antes de publicar.
insert into public.products (id,name,category,price,unit,description,image,sizes,colors,availability,visible) values
(1, 'Pijama Americano', 'pijama', 55, 'conjunto', 'Conjunto calÃ§a e camiseta quentinho e estampado, ideal para noites confortÃ¡veis e femininas.', '/catalog/product-1.png', ARRAY['P','M','G','GG']::text[], ARRAY['Rosa','Azul','LilÃ¡s']::text[], 'encomenda', true),
(2, 'Camisola de Renda', 'lingerie', 60, 'peÃ§a', 'Camisola elegante com detalhes em renda delicada, perfeita para noites especiais e presentes.', '/catalog/product-2.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Rosa','Branco','Preto','Vinho']::text[], 'encomenda', true),
(3, 'Baby Doll', 'lingerie', 55, 'conjunto', 'Conjunto baby doll curto e delicado, confortÃ¡vel e feminino para dias quentes.', '/catalog/product-3.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Rosa','Preto','Branco']::text[], 'encomenda', true),
(4, 'Baby Doll Suede', 'lingerie', 50, 'conjunto', 'Baby doll em tecido suede macio e sofisticado, leve e com toque aveludado.', '/catalog/product-4.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Rosa','Nude','Vinho','Preto']::text[], 'encomenda', true),
(5, 'Conjunto Infantil Americano', 'pijama', 50, 'conjunto', 'Conjunto pijama infantil estampado, macio e confortÃ¡vel para as crianÃ§as.', '/catalog/product-5.webp', ARRAY['2','4','6','8','10','12']::text[], ARRAY['Rosa','Azul','Verde']::text[], 'encomenda', true),
(6, 'Macaquito Suede', 'lingerie', 40, 'peÃ§a', 'Macaquito feminino em suede aveludado, estiloso e confortÃ¡vel para o dia a dia.', '/catalog/product-6.jpg', ARRAY['P','M','G','GG']::text[], ARRAY['Nude','Rosa','Preto','BordÃ´']::text[], 'encomenda', true),
(7, 'Lingerie Renda Bordada', 'lingerie', 60, 'conjunto', 'Conjunto lingerie com renda bordada de alta qualidade, sofisticado e delicado.', '/catalog/product-7.jpg', ARRAY['P','M','G','GG']::text[], ARRAY['Preto','Vinho','Rosa','Nude']::text[], 'encomenda', true),
(8, 'Lingerie de Renda', 'lingerie', 50, 'conjunto', 'Conjunto lingerie em renda delicada, confortÃ¡vel e feminina para o dia a dia.', '/catalog/product-8.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Preto','Rosa','Branco','Vermelho']::text[], 'encomenda', true),
(9, 'Calcinha Semi Fio', 'calcinha', 5, 'unidade', 'Calcinha semi fio em renda delicada. Vendida por unidade â€” compre quantas quiser!', '/catalog/product-9.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Preto','Rosa','Branco','Vinho','Bege']::text[], 'disponivel', true),
(10, 'Calcinha Normal', 'calcinha', 6, 'unidade', 'Calcinha bÃ¡sica confortÃ¡vel em renda. Vendida por unidade.', '/catalog/product-10.webp', ARRAY['P','M','G','GG']::text[], ARRAY['Preto','Rosa','Branco','Bege','Azul']::text[], 'disponivel', true),
(11, 'Sabonete Artesanal', 'sabonete', 10, 'unidade', 'Sabonete decorativo artesanal de alta qualidade. Perfeito para usar ou presentear. Formatos variados.', '/catalog/product-11.jpg', ARRAY[]::text[], ARRAY['Rosa','Branco','LilÃ¡s','PÃªssego']::text[], 'encomenda', true),
(12, 'Sabonete Caseiro Artesanal', 'sabonete', 10, 'unidade', 'Sabonete caseiro artesanal disponÃ­vel em qualquer fragrÃ¢ncia. ProduÃ§Ã£o sob encomenda com materiais selecionados.', '/catalog/product-12.jpg', ARRAY[]::text[], ARRAY['Qualquer fragrÃ¢ncia']::text[], 'encomenda', true)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.products', 'id'), greatest(coalesce((select max(id) from public.products), 1), 1));

