create table public.catalog_admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.catalog_admins enable row level security;
revoke all on public.catalog_admins from anon, authenticated;
grant select on public.catalog_admins to authenticated;
create policy "Admin can check own access" on public.catalog_admins
  for select to authenticated using (user_id = (select auth.uid()));

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 120),
  category text not null check (category in ('pijama', 'lingerie', 'calcinha', 'sabonete')),
  price numeric(10,2) not null check (price >= 0),
  unit text not null check (length(trim(unit)) > 0),
  description text not null default '',
  image text not null check (image ~ '^(https://|/catalog/)'),
  sizes text[] not null default '{}',
  colors text[] not null default '{}',
  availability text not null default 'encomenda' check (availability in ('disponivel', 'encomenda', 'indisponivel')),
  visible boolean not null default true
);
alter table public.products enable row level security;
revoke all on public.products from anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert, update on public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;
create policy "Visitors see visible products" on public.products
  for select to anon, authenticated using (visible = true);
create policy "Admins see full catalog" on public.products
  for select to authenticated using (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));
create policy "Admins create products" on public.products
  for insert to authenticated with check (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));
create policy "Admins edit products" on public.products
  for update to authenticated
  using (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())))
  with check (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-photos', 'product-photos', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']);
create policy "Admins upload product photos" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'product-photos' and exists (select 1 from public.catalog_admins where user_id = (select auth.uid()))
  );
